// Generated by CoffeeScript 1.6.3
var WormRun, worm;

WormRun = (function() {
  function WormRun() {}

  WormRun.prototype.wormStep = function(stepFrom, stepTo) {
    var stepCount, wormPosEnd, wormPosStart, wormWidth;
    wormPosStart = stepFrom * 20;
    stepCount = stepTo - stepFrom;
    wormWidth = Math.abs(stepCount) * 20 + 16;
    wormPosEnd = stepCount * 20 + wormPosStart;
    if (stepCount > 0) {
      return $('.worm').animate({
        'width': wormWidth
      }, 400, function() {
        return $('.worm').animate({
          'width': 16 + 'px',
          'left': wormPosEnd + 'px'
        }, 400);
      });
    } else {
      return $('.worm').animate({
        'width': wormWidth,
        'left': wormPosEnd + 'px'
      }, 400, function() {
        return $('.worm').animate({
          'width': 16 + 'px'
        }, 400);
      });
    }
  };

  return WormRun;

})();

worm = new WormRun();

$(document).on('click', '.control-elem', function() {
  var activeIndex, targetIndex;
  activeIndex = $('.control-elem.active').index();
  targetIndex = $(this).index();
  $('.control-elem.active').removeClass('active');
  $(this).addClass('active');
  return worm.wormStep(activeIndex, targetIndex);
});
